name: template_flutter
description: "A template Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.0
  get_storage: ^2.1.1
  collection: ^1.16.0
  path_provider: ^2.1.3
  mocktail: ^1.0.3
  firebase_core: ^2.28.0
  firebase_remote_config: ^4.4.0
  firebase_analytics: ^10.10.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.1.2
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

  flutter_lints: ^3.0.0

build_runner:
  carriers:
    json_serializer:
      builder: JsonSerializableGenerator
      inputs:
        - package:template_flutter/lib

flutter:
  uses-material-design: true
